### ISSUE TITLE
Naming of Param objects

### ISSUE THREAD

**Issue by michaelwitting** [rformassspectrometry/MetaboAnnotation#18]
Naming of `TargetMass2MzParam` is confusing, since it implies you are only working on specific targets (which is the case in `MzParam`). I'm suggesting to rename it to e.g. `AdductMzParam` or similar to make clear that it first calculates adducts and then annotates measured m/z values.

**Comment by jorainer** [comment]
I think we have the following situations:

- query m/z, target m/z: `MzParam`, since we're matching m/z against m/z directly.
- query m/z, target mass: need to convert the target mass first to m/z to compare. Original name of the Param class was `TargetMass2MzParam` to describe that conversion, but it might indeed be confusing. I'm OK with renaming `AdductMzParam` because we're converting mass -> m/z for selected adducts.

Another point of confusion might be that we now also use `matchMz` to match on m/z **and** retention time - using the `MzRtParam` (and then `AdductMzRtParam`) param objects. I would still like to keep it this way instead of adding an additional `matchMzRt` method - is that OK for you @michaelwitting ?

**Comment by michaelwitting** [comment]
I'm totally fine with having one method and differentiate based on the parameter.
I'm just wondering if we need `AdductMzRtParam` from a practical point of view. If you don't know you m/z value, how should you know the RT? Typically, you would use this only for metabolites for which you have already measured standards. So `MzParam` and `MzRtParam` makes sense.

**Comment by jorainer** [comment]
Wait, but `MzParam` at present assumes you have m/z as input (query) **and** m/z against which you want to compare (target or reference). If you have m/z as input and mass as reference you need to calculate m/z values from the mass **before** you can compare against the query m/z. We have called that `TargetMass2MzParam` (because the function `MetaboCoreUtils::mass2mz` function was used to calculate the `Target` mass to m/z). This conversion needs the definition of adducts. Now, to make that easier on the user, I thought we rename `TargetMass2MzParam` -> `AdductMzParam`. 

Next level would be if we had also the retention times available: `MzParam` -> `MzRtParam`. `AdductMzParam` -> `AdductMzRtParam`. I guess what you mean now, when saying that you measure standards is that you know already the RT **and** the m/z of the specific ion of a standard - in which case you will have a database with m/z and RT values as reference and you could use the `MzRtParam`. If you have the RT and just the *compound* info (i.e. the exact mass) you would need to use the `AdductMzRtParam` instead (convert mass to m/z with adduct info).

Thinking all over again, I think the `TargetMass2MzParam` was not such a bad name in the end...

**Comment by michaelwitting** [comment]
Maybe we can remove the `Target` to only have `Mass2MzParam`?

On the other point: If you even don't know which adduct it is and therefore whichm m/z, how should you know the RT. Therefore, in practical point of view `Mass2MzRtParam` doesn't make sense. Of course we can add it, but I would think I would never use it.

**Comment by jorainer** [comment]
Agree `Mass2MzParam` sounds great - without the misleading `Target`.

Never say you'll never use it :) I would add it for completeness reasons.

@andreavicini , can you please remove the `Target` from the names of all param objects? and please also update/fix the documentation accordingly, the unit tests and the vignette.

**Comment by michaelwitting** [comment]
If I find time, I would implement a `MzRtCssParam` with the methods for also having CCS values matching in their.
