### ISSUE TITLE
number of common peaks in @matches

### ISSUE THREAD

**Issue by stanstrup** [rformassspectrometry/MetaboAnnotation#36]
It would be nice to have the number of common peaks in `@matches` in addition to `presence_ratio`. When I take a quick look at matches I'd like to see if for example only a single peak was matched.

**Comment by jorainer** [comment]
Sure, makes sense.

**Comment by jorainer** [comment]
@stanstrup , can you check if you're happy with the recent changes and eventually close the issue?

**Comment by stanstrup** [comment]
It seems to always return 1...

**Comment by jorainer** [comment]
OMG, you're right @stanstrup ! Instead of adding the number of common peaks for one match I always replaced the whole column (see https://github.com/rformassspectrometry/MetaboAnnotation/commit/4788bbc962277dece8a92e4063fb895bfdee26ff)! I'm really sorry for this terrible bug! Thanks for checking and reporting! It should be fixed now.

**Comment by stanstrup** [comment]
It is me that thanks you for bothering with my request. It works now. Thanks!
