### ISSUE TITLE
Support for QFeatures

### ISSUE THREAD

**Issue by michaelwitting** [rformassspectrometry/MetaboAnnotation#67]
`QFeatures` are an extension of `SummarizedExperiment` specific for MS data. Shall we add support for this as well.  We (@chufz and myself) are using `QFeatures` within our annotation workflow (https://github.com/michaelwitting/MetaboliteAnnotationWorkflow).

**Comment by jorainer** [comment]
Sure! Sounds like a great idea - but it's not directly extending `SummarizedExperiment`, right? In that case it should already work right away. Does it have something like `rowData` or where are you storing the annotation in a `QFeatures`?

**Comment by michaelwitting** [comment]
Yes, you can access the annotations via `rowData`.

**Comment by jorainer** [comment]
Hm, but then the solution might be very easy to simply define a `classUnion` for `QFeatures` and `SummarizedExperiment`? Maybe @andreavicini could you have a look into that?

**Comment by andreavicini** [comment]
Yes, I think too it should work that way. I'll look into it.

**Comment by jorainer** [comment]
Yes, the `QFeatures` extends the `MultiAssayExperiment` - so maybe the best would be to support that class - then we would get the `QFeatures` *for free*.

**Comment by jorainer** [comment]
`MultiAssayExperiment` is defined [here](http://bioconductor.org/packages/release/bioc/html/MultiAssayExperiment.html)

**Comment by andreavicini** [comment]
As far as I understood these objects contain a list of experiments that generally are `SummarizedExperiment`s but can also be other two dimensional object such as `matrix`.  Our `matchValue`  function should get the `rowData` of one of those experiments (in case they are matrix maybe throw an error) and perform the match on that, right? Also the question is which one? Should we add an additional parameter to `matchValue` so that the user can choose? And maybe we should add an additional slot to the `Matched` (or new object inheriting from it) with the index or name of the experiment whose `rowData` was used for the match. What do you think?

**Comment by michaelwitting** [comment]
Yes, the user would need to define the assay that shall be used. I agree to have a slot in `Matched` object or object derived from it.

**Comment by jorainer** [comment]
Agree. For `QFeatures` or `MultiAssayExperiments` `matchValues` would gain an additional parameter `assayName` that defines which of the assays should be used. This needs then also to be stored in the `Matched` object. Question is whether in an additional slot in `Matched` or in a new class... it depends a bit what is less complicated. I have presently the feeling that it is easier to just add a new slot. We can later always define a new object...

**Comment by jorainer** [comment]
This is implemented with PR #80
